DROP TABLE F18_2_CUSTOMER PURGE;
DROP TABLE F18_2_DELIVERS PURGE;
DROP TABLE F18_2_DELIEVERY_AGENT;
DROP TABLE F18_2_MENU_ITEM PURGE;
DROP TABLE F18_2_ORDERS PURGE;
DROP TABLE F18_2_RESTAURANT PURGE;
DROP TABLE F18_2_RESTAURANT_TIMES PURGE;
DROP TABLE F18_2_WORKS_FOR PURGE;